# Generated by Django 4.1.3 on 2022-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=128)),
                ('doctor', models.CharField(max_length=128)),
            ],
        ),
    ]
