# Generated by Django 4.1.3 on 2022-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lecture_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(default='ss'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='part_num',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
