# Generated by Django 4.1.3 on 2022-11-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_book_lecture_num_book_link_book_part_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='part_num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
